### ISSUE TITLE
OpenTok don't work with most recent versions in Swift used in < Xcode 10.2

### ISSUE THREAD

**Issue by misterpoloy** [opentok/opentok-react-native#274]
# Bug Report

**Current behavior**
> Integrate openTok on versions of Xcode greater than 10.2

**Steps to reproduce**
> Update Xcode to the most recent version that does not support Swift `3.x`

**What is the current *bug* behavior?**
> Since the last update Xcode does not support swift `3.x` and older.

**Relevant logs and/or screenshots**
<img width="427" alt="Screen Shot 2019-04-24 at 11 58 08 AM" src="https://user-images.githubusercontent.com/22797958/56680161-550ed200-668c-11e9-9c44-38b8d8687aa8.png">

**Comment by Esbruiz** [comment]
This is also happening to us, we suspect this is algo causing problems with our builds in appcenter. Locally we can build using xcode 10.1, but we can't archieve or make releases because of this. Have any ETA on when this will be fixed? @evillemez  @msach22

**Comment by msach22** [comment]
@misterpoloy @Esbruiz Hmm, the latest version uses Swift 4.2

Could you please confirm you're using the latest version of this library?

**Comment by evillemez** [comment]
@msach22 We're having the same problem with old and new versions of the library.

Our current released branch uses an old version... it built fine a week ago, but breaks now.

One of our development versions uses the latest version, it also built fine a week ago, but breaks now.

**Comment by evillemez** [comment]
I can get you the build logs from AppCenter for builds using both the old, and a latest lib versions if that would help... ?

**Comment by msach22** [comment]
Hmm that's interesting - it shouldn't just break because the SWIFT_VERSION is set to 4.2: https://github.com/opentok/opentok-react-native/blob/master/ios/OpenTokReactNative.xcodeproj/project.pbxproj#L316

Please go ahead and email me the logs :)

**Comment by evillemez** [comment]
@msach22 

An update on the issues I and @Esbruiz commented on: It turns out the iOS SDK version was not specified in our Podfile, so the version that was actually being pulled in during build time was unpredictable.

I'm not sure at this point if our issue was related to the original issue posted here. So, for anyone who comes across this: check that your Podfile is actually specifying the version declared in the README for the version of `opentok-react-native` you are using.

**Comment by msach22** [comment]
Thanks @evillemez. It's important to lock in an SDK version so you can have consistency in your testing. Are you still seeing this when you lock in an SDK version?

**Comment by evillemez** [comment]
@msach22 Yeah, locking in the SDK version in the Podfile fixed our build problems - but I'm not sure if it's the solution to the original issue posted here.

@misterpoloy Have you checked that your Podfile specifies the correct version of the iOS SDK?

**Comment by msach22** [comment]
@evillemez Locking in the SDK is very important IMHO (this way you can have consistency across the dev team).

Please note that you need to use v0.9.6 and above for Swift 4.2. Could you confirm that's the version you're using?

**Comment by msach22** [comment]
Closing this issue because this has been resolved for the developer (communicated via email). Seems like there was a mismatch when compiling the OpenTokReactNative library (using older version)

**Comment by misterpoloy** [comment]
@msach22 Thanks! should `0.10.2` has the fix?

**Comment by misterpoloy** [comment]
> Closing this issue because this has been resolved for the developer (communicated via email). Seems like there was a mismatch when compiling the OpenTokReactNative library (using older version)

@msach22 what does this means? What are the next steps?
I still getting this error.
`pod 'OpenTok', '2.15.2'`
`"opentok-react-native": "0.9.4",`

**Comment by evillemez** [comment]
@msach22 I don't think my issue was actually the same as @misterpoloy.  It sounded the same at first to me, so I commented here, but it should probably be reopened.
