### ISSUE TITLE
Android crash: Exception in native call from JS

### ISSUE THREAD

**Issue by tomek29k** [opentok/opentok-react-native#357]
# Bug Report

Android (Galaxy S9):
`opentok-android-sdk@2.16.2`
`opentok-react-native@0.12.1`

**Current behavior**
> Crashes when disconnecting from the call.
> Happens when `OTSessionManager.java` calls the SDK method `mSession.disconnect()` of `Session.java`.

**Steps to reproduce**
> Just leave the call on Android with other users (doesn't happen every time though). 

**Relevant logs and/or screenshots**

![Screenshot_20190926-145530_29k dev](https://user-images.githubusercontent.com/52274775/66126009-ae3e4280-e5e8-11e9-8986-de23aa4d2ad3.jpg)

**Comment by sharon-systalent** [comment]
Any updates on this? I am having the same issue.

**Comment by ASerga** [comment]
I have the same issues with the same RN red-box error and traceback.

It happens ONLY while disconnecting the session that has screen sharing subscriber.
Maybe because I use this branch https://github.com/ggoldens/opentok-react-native/tree/fix-destroy-publisher (current master branch on `opentok-react-natvie` has issues on Android)

On the screenshot - Java row that triggers the crash. 

<img width="1748" alt="Screen Shot 2019-10-22 at 8 56 12 PM" src="https://user-images.githubusercontent.com/33656379/67315120-96365080-f50e-11e9-99e9-8f32c6e33ee7.png">

@ggoldens do you need more feedback?

**Comment by HeroSony** [comment]
I have the same issue, like @tomek29k mentioned.
`opentok-android-sdk@2.16.2`
`opentok-react-native@0.12.1`

Currently I implemented Live-Room-Video-Chat (one-to-one).
- room (sessionId) 
- owner (room owner)
- guest (joining room)

```
<OTSession
  ref={this.otSessionRef}
  apiKey={roomInfo.apiKey}
  sessionId={roomInfo.sessionId}
  token={roomInfo.token}
  eventHandlers={this.sessionEventHandlers}
>
  <View style={{ flex: 5}}>
    <OTPublisher
      properties={this.publisherProperties}
      eventHandlers={this.publisherEventHandlers}
      style={{ flex: 1 }}
    />
  </View>

  <View
    onLayout={event => {
      this.find_dimesions(event.nativeEvent.layout);
    }}
    style={{ flex: 5 }}
  >
    <OTSubscriber
      properties={this.subscriberProperties}
      eventHandlers={this.subscriberEventHandlers}
      style={{ flex: 1 }}
      streamProperties={this.state.streamProperties}
    />
  </View>
</OTSession>
```
Above example code disconnect guest session using signal from owner and working fine.
```
<OTSession
  ref={this.otSessionRef}
  apiKey={roomInfo.apiKey}
  sessionId={roomInfo.sessionId}
  token={roomInfo.token}
  eventHandlers={this.sessionEventHandlers}
>

  <View style={{ flex: 5}}>
    
     // Creating another Virtual Publisher
     <OTPublisher
       properties={this.virtualPublisherProperties}
       eventHandlers={this.virtualPublisherEventHandlers}
        style={{ height: 0, overflow: 'hidden', }}
    />

    <OTPublisher
      properties={this.publisherProperties}
      eventHandlers={this.publisherEventHandlers}
      style={{ flex: 1 }}
    />
  </View>

  <View
    onLayout={event => {
      this.find_dimesions(event.nativeEvent.layout);
    }}
    style={{ flex: 5 }}
  >
    <OTSubscriber
      properties={this.subscriberProperties}
      eventHandlers={this.subscriberEventHandlers}
      style={{ flex: 1 }}
      streamProperties={this.state.streamProperties}
    />
  </View>
</OTSession>
```
Above example code, after trying to create a new virtual publisher(attempt to streaming external music in to session) disconnect guest session using signal from owner and produce error:

![image](https://user-images.githubusercontent.com/4160246/67567932-1b12ab80-f755-11e9-8b93-aea14ea66887.png)

**Comment by dennistjahyadi** [comment]
i have the same issues. I try to do gradlew clean in folder reactNativeProject/android
,then i run-android, 
and react-native start --reset-cache..
it's working now

**Comment by dennistjahyadi** [comment]
i have the same issues. Any Updates?

**Comment by aslampr07** [comment]
As a workaround edit  `node_module/opentok-react-native/andorid/build.gradle`,
and change the line from
`implementation 'com.opentok.android:opentok-android-sdk:2.16.1`  to
`implementation 'com.opentok.android:opentok-android-sdk:2.16.2`

**Comment by ASerga** [comment]
> As a workaround edit `node_module/opentok-react-native/andorid/build.gradle`,
> and change the line from
> `implementation 'com.opentok.android:opentok-android-sdk:2.16.1` to
> `implementation 'com.opentok.android:opentok-android-sdk:2.16.2`
> 
> It is causing the crash because the react version still using an older native SDK. The newest SDK has fixed the crashing problem. [see link](https://tokbox.com/developer/sdks/android/release-notes.html)

@aslampr07 I already use `v2.16.2`. Yes, it helps, but still there is a crash while disconnecting the session that has screen sharing subscriber.

**Comment by aslampr07** [comment]
@ASerga can you please checkout the branch '0.12.2' of this repository I think they have fixed the issue, but haven't merged with the master branch.

**Comment by ASerga** [comment]
@aslampr07 I have tried. It didn't help.

**Comment by ggoldens** [comment]
Hello guys, apologize for the inconveniences and the delay on this. It looks that there's an issue on the native SDK. I am able to reproduce this issue with a pure android app. I just reported it to the native team. Will keep you posted. 

Thanks for reporting!

**Comment by op** [comment]
@ggoldens We seem to experience this problem all the time. Any updates? :pray:

**Comment by ASerga** [comment]
> @ggoldens We seem to experience this problem all the time. Any updates? 🙏

Yes, It's really critical :( 
@ggoldens is there an issue in Opentok Android SDK?

**Comment by enricop89** [comment]
We released today Android SDK 2.16.3 patch.
Please try to update the version on android/build.gradle file and test the issue.

**Comment by QuevedoIB** [comment]
Tried updating versions, still having problems: 

React Native version: 0.59.5
opentok-react-native version: 0.12.1
OpenTok Android SDK version: 2.16.3

Throws an error for OTSession connect expecting 3 arguments and instead receiving 2.

https://github.com/opentok/opentok-react-native/issues/366#issuecomment-562043082

**Comment by ggoldens** [comment]
Can you guys test the branch 0.12.2? If you see it ok I'll push it asap.
Thanks!

**Comment by ggoldens** [comment]
FYI v0.12.2 it's released. Please confirm us if you still see the issue. Thanks!

**Comment by tomek29k** [comment]
Hi Germán,

It seems SDK 2.16.3 has solved the problem for us, haven't tried v0.12.2
yet but will try today.

Many thanks!
/Tomek

**Comment by ggoldens** [comment]
Thanks for the feedback @tomek29k !

**Comment by ggoldens** [comment]
Will close this issue since it seems to be solved using the latest android SDK.
