### ISSUE TITLE
Video is not streaming on IOS

### ISSUE THREAD

**Issue by billy220** [opentok/opentok-react-native#577]
## Current behavior
I can see my own video, but not the video of anyone else in the session. Android works just fine. 

## What is the current bug behavior?
Can't see other people's videos on ios
Subscriber eventhandler videoDataReceived not work
![image](https://user-images.githubusercontent.com/96406881/153154158-77752fa7-199c-45b9-b26c-262dc16a7818.png)

```
"react-native": "0.66.4",
```

## What is the expected correct behavior?
Can see other people's videos on ios

**Comment by billy220** [comment]
It was because of the 'react native webrtc' we were using together, so we close the issue.

**Comment by rajasekhar911** [comment]
hi
can you please let us know how this issue was resolved? we are also using the react-native-webrtc for another feature and opentok video stopped working in ios. 
thanks

**Comment by cesa1995** [comment]
I still have the same issue, all work fine without react-native-webrtc, any update?
